name: Run tests

on: [push]

jobs:  
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
        mongodb-version: [3.6,4.0]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB v${{ matrix.node-version }}
      uses: superchargejs/mongodb-github-action@1.0.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}


    - run: npm install && ls
    - run: npm test 
      timeout-minutes: 2
      env:
        CI: true
